/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomInput: typeof import('./../.vitepress/theme/components/CustomInput.vue')['default']
    Home: typeof import('./../.vitepress/theme/home.vue')['default']
  }
}
